services:
  - type: web
    name: plugin-vault-backend
    env: node
    plan: free
    buildCommand: npm ci --omit=dev
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true 